apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      name:  {{ .Values.service.name }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        customlabel: success
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}
          imagePullPolicy: IfNotPresent
